### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by isaiahdw** [heroku/heroku-releases-retry#6]
This use to work for me, but I think something with the latest heroku API/cli caused it to stop working.

I get the following error when trying to retry a release:

```Cannot read property 'id' of null```

**Comment by dmathieu** [comment]
Could you run `HEROKU_DEBUG=* heroku releases:retry`?
Also, how many releases (failed and succeeded) does the app have?

**Comment by edelgado** [comment]
It seems to fail on this line: https://github.com/heroku/heroku-releases-retry/blob/master/commands/retry.js#L19

In my case, the app failed to deploy. I modified some config, and wanted to retry using this plugin. Maybe there is nothing to retry if an app has never deployed successfully?

**Comment by dmathieu** [comment]
Thank you. We'll be looking into this.
And yes, in order to have something to retry, you need a successful build (not a deploy). If there is no successful build, there can't be a failed release.
