### ISSUE TITLE
retry hangs indefinitely

### ISSUE THREAD

**Issue by SampsonCrowley** [heroku/heroku-releases-retry#9]
I have two rails based apps that share a common code base and database. Both apps had a commit pushed at the same time. The first app had migrations to run. this puts a lock on the database. second app failed release due to db lock. no big deal, just run a retry when first app is done migrating

upon running `heroku releases:retry` the release is just stuck doing nothing even though there's not actually anything it needs to do to finish the release. viewing the live log shows "release finished" after loading, but the activity log still shows as retrying

![Screenshot from 2019-05-07 15-58-19](https://user-images.githubusercontent.com/22461638/57336434-1a248980-70e3-11e9-9c6a-1ecab2174cf5.png)
![Screenshot from 2019-05-07 15-58-32](https://user-images.githubusercontent.com/22461638/57336435-1a248980-70e3-11e9-91b7-6d1ea40c44d3.png)
![Screenshot from 2019-05-07 15-58-48](https://user-images.githubusercontent.com/22461638/57336436-1abd2000-70e3-11e9-8bc2-d171604ec4e7.png)

**Comment by dmathieu** [comment]
This isn't an issue with the buildpack, but rather with your release dyno.
Please open a support ticket at help.heroku.com instead.

**Comment by SampsonCrowley** [comment]
no it is ONE HUNDRED percent a problem with this buildpack. leaving **active-tense** verbs in a log for a situation that is complet**ed* (**past-tense**) so that users **HAVE** to inspect their logs to know if the retried releases was successful and second guess if that is actually the case, or not is terrible UX

**Comment by SampsonCrowley** [comment]
While I did in fact misinterpret what should be present in the activity log, as there is nothing wrong with my dyno; the release completed just fine, this buildpack doesn't reflect that state when it reaches it. I honestly don't know how I'm the first person to find this to be ambiguous
